# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
    - ### np.save("파일경로", 배열)
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 npy를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러온다.
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - 여러개의 배열을 저장할 때 사용
        - 파일명에 확장자로 npz가 붙는다.
        - 내부적으로 압축해서 저장한다.
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로", 배열 [, delimiter='공백') 
        - 텍스트 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 10, 5, 7, 20])
b = np.ones(shape=(3,3,5))
c = np.random.normal(10, 2, size=(5,10)) #평균:10, 표준편차:2
print(a.shape, b.shape, c.shape)

(5,) (3, 3, 5) (5, 10)


In [4]:
c

array([[ 9.85507964,  8.74389819, 10.5432437 ,  9.88132399, 11.24013951,
        11.86827441,  8.93554885,  8.92523584,  7.73962245,  8.07562326],
       [12.54390172, 10.31272131,  6.57384419,  8.58487796, 12.71635954,
        15.45282453, 11.79545514, 15.69102622, 10.43038945, 10.51874627],
       [11.46865257,  6.86697031, 12.3417728 ,  8.68264378,  8.63354331,
        13.36668951, 10.62142413,  9.02298617,  9.86788052,  9.41268691],
       [10.97830204, 10.3856375 ,  7.93572779, 11.97609303, 11.51796863,
        12.20372254, 10.6239629 ,  8.14138097,  8.10688614,  9.78775771],
       [ 7.47387521,  9.584049  , 13.17684812,  8.88672815,  9.44551362,
        11.33483513, 10.80281743,  8.03670579,  9.89282201, 10.24160671]])

In [3]:
# binary 파일에 배열을 저장
# 한파일에 하나에 배열 - save(경로, 배열)
# 경로: 상대경로(현재 working directory 기준 경로), . : 현재디렉토리, ..: 상위디렉토리
#       절대경로(root 디렉토리부터 전체 경로) - c:\a\b\abc
np.save("data/array_a", a)  #data/array_a.npy
np.save("data/array_b.npy", b)
np.save("data/array.c", c) #data/array.c.npy

In [5]:
# 불러오기(load) - load()
a2 = np.load('data/array_a.npy')
b2 = np.load('data/array_b.npy')
c2 = np.load('data/array.c.npy')

In [6]:
a2.shape, b2.shape, c2.shape

((5,), (3, 3, 5), (5, 10))

In [7]:
a2

array([ 1, 10,  5,  7, 20])

In [8]:
b2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
c2

array([[ 9.85507964,  8.74389819, 10.5432437 ,  9.88132399, 11.24013951,
        11.86827441,  8.93554885,  8.92523584,  7.73962245,  8.07562326],
       [12.54390172, 10.31272131,  6.57384419,  8.58487796, 12.71635954,
        15.45282453, 11.79545514, 15.69102622, 10.43038945, 10.51874627],
       [11.46865257,  6.86697031, 12.3417728 ,  8.68264378,  8.63354331,
        13.36668951, 10.62142413,  9.02298617,  9.86788052,  9.41268691],
       [10.97830204, 10.3856375 ,  7.93572779, 11.97609303, 11.51796863,
        12.20372254, 10.6239629 ,  8.14138097,  8.10688614,  9.78775771],
       [ 7.47387521,  9.584049  , 13.17684812,  8.88672815,  9.44551362,
        11.33483513, 10.80281743,  8.03670579,  9.89282201, 10.24160671]])

In [14]:
# 한파일에 여러개 배열 - savez(경로, 이름1=배열, 이름2=배열, ...)
np.savez("data/array", a=a, b=b, c=c) #data/array.npz

In [15]:
arrays = np.load('data/array.npz')
arrays

In [16]:
# 배열들의 이름들을 조회
arrays.files

['a', 'b', 'c']

In [18]:
# 각 배열을 조회 - index연산자 사용
a3 = arrays['a']
b3 = arrays['b']
c3 = arrays['c']

In [19]:
a3

array([ 1, 10,  5,  7, 20])

In [21]:
b3.shape

(3, 3, 5)

In [23]:
c3

array([[ 9.85507964,  8.74389819, 10.5432437 ,  9.88132399, 11.24013951,
        11.86827441,  8.93554885,  8.92523584,  7.73962245,  8.07562326],
       [12.54390172, 10.31272131,  6.57384419,  8.58487796, 12.71635954,
        15.45282453, 11.79545514, 15.69102622, 10.43038945, 10.51874627],
       [11.46865257,  6.86697031, 12.3417728 ,  8.68264378,  8.63354331,
        13.36668951, 10.62142413,  9.02298617,  9.86788052,  9.41268691],
       [10.97830204, 10.3856375 ,  7.93572779, 11.97609303, 11.51796863,
        12.20372254, 10.6239629 ,  8.14138097,  8.10688614,  9.78775771],
       [ 7.47387521,  9.584049  , 13.17684812,  8.88672815,  9.44551362,
        11.33483513, 10.80281743,  8.03670579,  9.89282201, 10.24160671]])

In [24]:
# text 파일로 저장 => CSV (comma separated value). 1차원, 2차원 배열만 저장가능
#  savetxt(), loadtxt()

In [26]:
a

array([ 1, 10,  5,  7, 20])

In [25]:
np.savetxt('data/a.csv', a)

In [31]:
a4 = np.loadtxt('data/a.csv', dtype=np.int)

In [32]:
a4

array([ 1, 10,  5,  7, 20])

In [34]:
print(b.shape)
np.savetxt('data/b.csv', b) #3차원 이상 배열은 저장할 수 없다.

(3, 3, 5)


ValueError: Expected 1D or 2D array, got 3D array instead

In [35]:
c.shape

(5, 10)

In [36]:
np.savetxt('data/c.csv', c)

In [37]:
np.savetxt('data/c2.csv', c, delimiter=',')

In [39]:
c4 = np.loadtxt('data/c.csv')
print(c4.shape)
c4

(5, 10)


array([[ 9.85507964,  8.74389819, 10.5432437 ,  9.88132399, 11.24013951,
        11.86827441,  8.93554885,  8.92523584,  7.73962245,  8.07562326],
       [12.54390172, 10.31272131,  6.57384419,  8.58487796, 12.71635954,
        15.45282453, 11.79545514, 15.69102622, 10.43038945, 10.51874627],
       [11.46865257,  6.86697031, 12.3417728 ,  8.68264378,  8.63354331,
        13.36668951, 10.62142413,  9.02298617,  9.86788052,  9.41268691],
       [10.97830204, 10.3856375 ,  7.93572779, 11.97609303, 11.51796863,
        12.20372254, 10.6239629 ,  8.14138097,  8.10688614,  9.78775771],
       [ 7.47387521,  9.584049  , 13.17684812,  8.88672815,  9.44551362,
        11.33483513, 10.80281743,  8.03670579,  9.89282201, 10.24160671]])

In [44]:
c5 = np.loadtxt('data/c2.csv', delimiter=',')
c5.shape

(5, 10)